version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
